### PR TITLE
Non-static fonts

### PR DESCRIPTION
**Pull request by Krasapan**
Now mods can replace default fonts with custom ones

### CODE REVIEW

**Comment by mestiez** [comment]
This won't compile

**Comment by Krasapan** [comment]
oh
then I'll try something else and try to compile

**Comment by mestiez** [comment]
I think c751394 makes fonts moddable by not caching the fonts loaded during the loading screen.

**Comment by Krasapan** [comment]
> I think [c751394](https://github.com/studio-minus/madness-interactive-reloaded/commit/c7513942e8f85fa669b9d3ac7c5b5dca962f8c2f) makes fonts moddable by not caching the fonts loaded during the loading screen.

Nice

**Pull request closed without merging**
